### PR TITLE
Fixes typo in function being checked when preparing driver in case of unexpected failure

### PR DESCRIPTION
**Pull request by luislobo**
Fixes typo in function being checked when preparing driver in case of unexpected failure

### CODE REVIEW

**Review by mikermcneil — APPROVED** [review]
🙌 👏

**Comment by mikermcneil** [comment]
@luislobo thank you!  (And thanks Keaton!)

**Comment by sgress454** [comment]
👍 Any idea why @sailshq/socket.io-redis [doesn't show up in npm search](https://www.npmjs.com/search?q=%40sailshq%2Fsocket.io-redis)?

**Comment by luislobo** [comment]
@sgress454 that is really strange. @mikermcneil is the `@sailshq/socket.io-redis` set as public? I don't know actually if you can have it private and still be able to do `npm install @sailshq/socket.io-redis` (that I checked and works)... Weird!

**Comment by sgress454** [comment]
Looks like just a bug in their search.  The page [does exist](https://www.npmjs.com/package/@sailshq/socket.io-redis)!

**Pull request merged**
