### PR TITLE
[Fixes Sails#4201] Repair req.ip for Socket

### PR DESCRIPTION
**Pull request by Maelstrom96**
Also changed the implementation to get the ips from the 'x-forwarded-for' header to prevent spoofing.

### CODE REVIEW

**Comment by mikermcneil** [comment]
@Maelstrom96 thanks for looking into this!  hmm... seems like this should probably mirror the trustProxy configuration, right?  If the `trustProxy` config is not enabled, then ip sniffing should work like it does in express  (otherwise you can spoof anyway)

**Comment by sgress454** [comment]
@Maelstrom96 @mikermcneil On a similar note, if `trust proxy` _is_ enabled, should use [proxy-addr](https://www.npmjs.com/package/proxy-addr) to determine the correct IP based on the setting (since `trust proxy` can be set to other values besides `true` or `false`).

**Comment by Maelstrom96** [comment]
@mikermcneil @sgress454 Using [proxy-addr](https://www.npmjs.com/package/proxy-addr) the same way has express is doing it should be easy to do, but it would be a hack since the code is made to use the express req object.

I've looked at the code of [proxy-addr](https://www.npmjs.com/package/proxy-addr) and we would only need to populate the dummy req object with  ```{connection: {remoteAddress: options.socket.handshake.address}, headers: {'x-forwarded-for': options.socket.handshake.headers['x-forwarded-for']}}```

**Comment by mikermcneil** [comment]
@Maelstrom96 that makes sense to me  (and thank you for pinning the exact dep version 👍 )

**Comment by sgress454** [comment]
Alright checking this out now...

**Pull request merged**
